language: node_js
node_js:
  - "7.6.0"

before_install:
  #- npm install -g cordova ionic karma-cli
  - sudo apt-get install python-dev

install:
  #- npm install
  #- cd housekeeper
  - sudo python setup.py develop
  - cd ..

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - node_modules/typescript/bin/tsc --noemit
  - karma start --single-run --browsers Firefox ./test-config/karma.conf.js
  - cd housekeeper
  - pytest
