sudo: false

language: node_js
node_js:
  - "7.6.0"

install:
  - npm install -g cordova ionic karma-cli
  - npm install
  - cd housekeeper
  - python setup.py install
  - cd ..

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - node_modules/typescript/bin/tsc --noemit
  - karma start --single-run --browsers Firefox ./test-config/karma.conf.js
  - cd housekeeper
  - pytest
